version: "3"
services:
  server:
    image: ghcr.io/fedor-ches098/serverpy:latest
    command: python ./server.py
    ports:
      - 1234:1234
  client:
    image: ghcr.io/fedor-ches098/clientpy:latest
    command: python ./client.py
    network_mode: host 
    depends_on:
      - server
